%-----------------------------------------------------------------------
% Job saved on 16-Mar-2022 09:47:13 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.factorial_design.dir ={'/Users/bensmith/Documents/code/DEV_scripts/fMRI/fx/models/SST/level2/cg_following_failed_and_correct_stop_pss/attempt2_provisional/CGFollowingFS_RT/'};
matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = {
%SlowingCGFollowingFS
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV006/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV013/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV014/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV015/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV016/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV017/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV018/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV019/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV020/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV021/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV022/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV023/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV024/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV026/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV027/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV028/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV029/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV030/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV031/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV033/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV034/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV035/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV036/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV040/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV041/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV042/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV043/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV045/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV046/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV047/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV048/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV049/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV051/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV052/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV053/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV054/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV056/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV057/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV058/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV059/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV060/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV062/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV063/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV064/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV065/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV068/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV070/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV071/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV073/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV074/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV076/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV077/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV078/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV079/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV083/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV084/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV085/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV086/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV087/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV088/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV089/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV090/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV095/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV097/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV102/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV105/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV107/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV108/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV112/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV113/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV116/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV119/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV120/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV122/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV127/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV135/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV137/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV141/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV144/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV145/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV147/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV156/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV157/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV158/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV159/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV164/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV167/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV169/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV171/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV172/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV173/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV177/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV178/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV196/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV197/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV205/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV206/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV209/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV215/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV216/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV217/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV223/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV230/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV233/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV235/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV236/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV237/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV238/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV239/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV240/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV241/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV249/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV250/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV251/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV252/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV254/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV256/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV260/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV262/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV263/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV264/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV265/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV266/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV269/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV271/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV272/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV273/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV274/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV275/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV276/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV278/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV282/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV284/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV291/spmT_0004.nii,1'
'/Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_conditions_w_pss/sub-DEV293/spmT_0004.nii,1'
                                                          };
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;

