'''
This script is for screening participant based on their framewise displacement generated by fMRIPrep
'''

import pandas as pd
from glob import glob
import numpy as np
import os
import re

# Initiate output dataset 
outlierDf = pd.DataFrame(columns=['sub_id', 'acq_id', 'fd_mean', 'fd_max', 'fd_std', 0.5, 0.8, 1, 2], index=range(400))
threshold = [0.5, 0.8, 1.0, 2.0] # set a range of threshold. 2.0 is the voxel size
rowIdx = 0

# set directory parameters 
fMRIPrep_dir = "/projects/sanlab/shared/DEV/bids_data/rs_derivatives/fmriprep/"
tsv_fileNames = glob(os.path.join(fMRIPrep_dir, "sub-*/ses-wave1/func/sub-*_ses-wave1_task-rest_acq-*.tsv"))

# loop through each file
for file in tsv_fileNames:
    # extract subID and rs run id from the file
    sub_id= re.split('/|_|-', file)[11]
    acq_id = re.split('/|_|-', file)[22]
    print (f'start with subject {sub_id} run {acq_id}')

    outlierDf.at[rowIdx, 'sub_id'] = sub_id
    outlierDf.at[rowIdx, 'acq_id'] = acq_id

    # read the framewise displacement data from the tsv file
    fullDf = pd.read_csv(file, sep='\t')
    fd = fullDf["FramewiseDisplacement"].values

    # generate and record descriptive data
    fd_mean = round(np.nanmean(fd), 3)
    fd_max = round(np.nanmax(fd), 3)
    fd_std = round(np.nanstd(fd), 3)
    outlierDf.at[rowIdx, 'fd_mean'] = fd_mean
    outlierDf.at[rowIdx, 'fd_max'] = fd_max
    outlierDf.at[rowIdx, 'fd_std'] = fd_std

    # record the number of outliers based on different fd threshold
    for T in threshold:
        outliers = np.count_nonzero(fd > T)
        outlierDf.at[rowIdx, T] = outliers
    
    rowIdx = rowIdx + 1

# write the output csv file under the fMRIPrep directory
outlierDf.to_csv(os.path.join(fMRIPrep_dir, 'fd_screen.csv'), index=False)

# subset dataframe for those who had fd > 1 voxel size (2mm)
excludeDf = outlierDf[outlierDf[2] > 0 ]

# write the output csv file under the fMRIPrep directory
excludeDf.to_csv(os.path.join(fMRIPrep_dir, 'fd_outlier.csv'), index=False)