---
title: "DEV MRI notes"
author: "Dani Cosme"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: tango
    theme: united
    toc: true
    toc_float: 
      collapsed: TRUE
      smooth_scroll: TRUE
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# load packages
```{r}
library(tidyverse)
library(lubridate)
```

# load data
```{r}
notes = read.csv("DEV2_DATA_2019-04-25_0110.csv", na.strings = c("")) %>%
  rename("subjectID" = dev_id) %>%
  select(-redcap_event_name) %>%
  group_by(subjectID) %>%
  fill(everything(), .direction = "down") %>%
  fill(everything(), .direction = "up") %>%
  unique() %>%
  gather(session, date, -subjectID) %>%
  mutate(date = ymd(date)) %>%
  spread(session, date) %>%
  select(date_1, date_2)
```

# tidy data
```{r}
data.tidy = data %>%
  extract(folder, c("subjectID", "datetime"), "(DEV[0-9]{3})_(.*)", remove = FALSE) %>%
  extract(datetime, "date", "(.*)_.*", remove = FALSE) %>%
  mutate(datetime = ymd_hms(datetime),
         date = ymd(date))
```

# summarize
```{r}
sessions %>%
  gather(session, date, -subjectID) %>%
  filter(!is.na(date)) %>%
  group_by(session) %>%
  summarize(n = n())
```

# verify sessions
Check if there are too many sessions or if the session dates are incorrect
```{r}
(merged = data.tidy %>%
   select(-folder) %>%
   arrange(datetime) %>%
   group_by(subjectID) %>%
   mutate(session = sprintf("session%d", row_number())) %>%
   arrange(subjectID) %>%
   select(-datetime) %>%
   spread(session, date) %>%
   right_join(., sessions)) 

(merged.check = merged %>%
  mutate(correct_session1 = ifelse(session1 == date_1, 1, 0),
         correct_session2 = ifelse(session2 == date_2, 1, 0),
         check_order = ifelse(session1 == date_2 | session2 == date_1, 1, 0), #| session3 == date_2 | session4 == date_2
         duration = ifelse(!is.na(session2), session2 - session1, NA)) %>%
  filter(!correct_session1 == 1 | !correct_session2 == 1 |  duration < 24) %>% #!is.na(session3) | !is.na(session4) |
  select(subjectID, correct_session1, correct_session2, check_order, duration, date_1, session1, date_2, session2)) #session3, session4
```

Duplicates
```{r}
(duplicates = data.tidy %>%
  arrange(datetime) %>%
  left_join(., merged) %>%
  mutate(correct_session1 = ifelse(session1 == date_1, 1, 0),
         correct_session2 = ifelse(session2 == date_2, 1, 0),
         check_order = ifelse(session1 == date_2 | session2 == date_1 , 1, 0), #| session3 == date_2 | session4 == date_2
         duration = ifelse(!is.na(session2), session2 - session1, NA)) %>%
  select(folder, subjectID, datetime, correct_session1, correct_session2, check_order, duration, date_1, session1, date_2, session2) %>% #, session3, session4
  filter(datetime %in% data.tidy[duplicated(data.tidy$datetime),]$datetime))
```

Wrong session1 date
```{r}
merged.check %>%
  filter(!subjectID %in% duplicates$subjectID) %>%
  filter(!correct_session1 == 1)
```

Wrong session2 date
```{r}
merged.check %>%
  filter(!subjectID %in% duplicates$subjectID) %>%
  filter(!correct_session2 == 1)
```

Subs run on dates with messed up files
```{r}
dates = merged.check %>%
  filter(!subjectID %in% duplicates$subjectID) %>%
  ungroup() %>%
  gather(session, date, starts_with("session"), starts_with("date")) %>%
  select(date) %>%
  unique() %>%
  filter(!is.na(date))

data.tidy %>%
  filter(date %in% dates$date) %>%
  arrange(datetime) %>%
  left_join(., merged) %>%
  mutate(check1 = ifelse(session1 == date_1, 1, 0),
         check2 = ifelse(session2 == date_2, 1, 0),
         duration = ifelse(!is.na(session2), session2 - session1, NA)) %>%
  select(folder, subjectID, datetime, check1, check2, duration, date_1, session1, date_2, session2) #, session3, session4
```
