---
title: "Render PDF tables"
author:
  - name  : "Ben Smith"
    affiliation: 1
affiliation:
  - id  : "1"
    institution: "University of Oregon"    
date: "2023-04-24"
class: man
output: 
  word_document
  papaja::apa6_pdf:
    keep_tex: yes
  
header-includes   :
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(papaja)
```



```{r}
library(tidyverse)
Sys.setenv(R_CONFIG_ACTIVE = Sys.info()["nodename"])
print(Sys.info()["nodename"])
library(stargazer)
library(tidyverse)

dropbox_dir <- config::get("dev_analysis_data_dir")

#load(paste0(dropbox_dir,"/sst_paper_generation.Rdata"))
```



```{r}
# trial_neural_behav_roi_stop<-trial_neural_behav_roi %>% filter(trial_n>50 & condition %in% c("CorrectStop","FailedStop"))
# 
# trial_neural_behav_roi_stop<- trial_neural_behav_roi_stop %>% 
#   mutate(P_stop_trial_change_z_stop = (P_stop_trial_change-mean(P_stop_trial_change))/sd(P_stop_trial_change),
#          post_pre_rt_change_z_stop = (post_pre_rt_change_z-mean(post_pre_rt_change_z))/sd(post_pre_rt_change_z)
#          )
# 
# model_full_effects <- lme4::lmer(
#    med_post_trial_z ~ trial_n_s+ condition + P_stop_trial_change+ post_pre_rt_change + (1 +post_pre_rt_change  + P_stop_trial_change  | subid),
#   trial_neural_behav_roi %>% filter(trial_n>50 & condition %in% c("CorrectStop","FailedStop"))
#   )
# summary(model_full_effects)
# 
# model_no_rt<- lme4::lmer(
#    med_post_trial_z ~ trial_n_s+ condition + P_stop_trial_change + (1 +post_pre_rt_change  + P_stop_trial_change  | subid),
#   trial_neural_behav_roi %>% filter(trial_n>50 & condition %in% c("CorrectStop","FailedStop"))
#   )
# 
# anova(model_full_effects,model_no_rt)
# model_no_p_stop<- lme4::lmer(
#    med_post_trial_z ~ trial_n_s+ condition + post_pre_rt_change + (1 +post_pre_rt_change  + P_stop_trial_change  | subid),
#   trial_neural_behav_roi %>% filter(trial_n>50 & condition %in% c("CorrectStop","FailedStop"))
#   )
# 
# anova(model_full_effects,model_no_p_stop)
# 
# save(model_full_effects, model_no_p_stop, model_no_rt, file=paste0(dropbox_dir,"/sample_models.Rdata"))

```


```{r}
load(paste0(dropbox_dir,"/sample_models.Rdata"))
```

# stargazer

problem with stargazer is that it has anova output which isn't hte same as the `anova` function, and makes my analysis look bad :/
# papaja

```{r}


table_full_effects = apa_table(papaja::apa_print(model_full_effects))
table_full_effects

```



 

OK, seems like papaja won't compare two models. How about gt?


# gt

```{r}
#model_comparison_summary <- function(model_list){
model_list <- list("RT Only"=model_no_p_stop,
                   "Full model"=model_full_effects,
                   "P(Stop) Only"=model_no_rt
                   )

```

```{r}



present_estimate_with_std_error<-function(coef_row,dp=2){
  return(paste0(
    as.character(round(coef_row[["Estimate"]],dp)), " (", 
    as.character(round(coef_row[["Std. Error"]],dp)), ")"
    ))
}

custom_mixed_model_summary<-function(model){
  m_summary <- summary(model)
  fixed_effects = apply(m_summary$coefficients,1,present_estimate_with_std_error)
  return(fixed_effects)
}



fixed_effects_list <- sapply(model_list, custom_mixed_model_summary)

fixed_effects_df <- t(dplyr::bind_rows(fixed_effects_list))

model_comparison <- do.call(anova,unname(model_list))

anova_model_order <- rownames(model_comparison) %>% str_extract("\\d+") %>% as.numeric
#anova re-organizes its results depending on which are better fit.
#we can do the same to the rest of the data, or we can re-organize back to how we had it.


anova_raw_result_df <- t(data.frame(model_comparison)[,c("npar", "AIC", "BIC", "logLik", "Chisq","Pr..Chisq.")])
anova_reorganized_list <- rep(list(NA),length(anova_model_order))
#to re-orgnize back
for (ri in 1:length(anova_model_order)){
  anova_reorganized_list[[ri]] <- anova_raw_result_df[,which(anova_model_order==ri)]
}
anova_result_df_input_order <- do.call(rbind, anova_reorganized_list)
#or we can organize the fixed effects in terms of the anova
#I think that is better...
fixed_effects_df_anova_order <- fixed_effects_df[,anova_model_order] #%>% data.frame
#then we can merge it with the anova results
anova_low_precision<-c( "AIC", "BIC", "logLik")
anova_med_precision<-c("Chisq")
anova_p_precision<-c("Pr..Chisq.")
anova_results_tided<-anova_raw_result_df #%>% data.frame()
anova_results_tided[anova_low_precision,]<-round(anova_results_tided[anova_low_precision,],0)
anova_results_tided[anova_med_precision,]<-round(anova_results_tided[anova_med_precision,],2)
anova_results_tided[anova_p_precision,]<-format.pval(anova_results_tided[anova_p_precision,])

# fixed_effects_df_anova_order$group="Fixed effects"
# anova_results_tided$group="Best fit"
table_cells <- rbind(fixed_effects_df_anova_order,anova_results_tided) 

table_cells[is.na(table_cells)] <- ""
```


```{r}
library(gt)
table_cells
model_compare_table <- gt(data.frame(table_cells),rownames_to_stub = TRUE) %>%
  tab_stubhead(label="Parameter") %>%
  tab_spanner(
    label="Median Activity 4-10 s Post-Stop Signal"
  ) %>%
  tab_row_group(
    label = "Fixed effects",
    rows = 1:nrow(fixed_effects_df_anova_order)
  )


                
  
  
```


```{r asis="TRUE"}
gt::as_word(model_compare_table)
```


# other

could try sjPlot

