% not all subjects have all conditions because some, e.g., get no trials
% right while others get all trials right.
% these must be treated differently or may need to be excluded from some
% contrasts altogether.
% either way, we need to identify them.
% There are various ways of doing this, but considering this item's place
% inteh pipeline, it makes the most sense to extract information about
% conditions from the .mat files already generated by the multiconds file.

