%-----------------------------------------------------------------------
% Job saved on 16-Mar-2022 09:47:13 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
% spm('defaults','fMRI');
matlabbatch{1}.spm.stats.factorial_design.dir = {'/Users/denicia/DEV/DEV_scripts/fMRI/fx/models/WTP/level2/prepostWTP_20230816/HealthyLiked(T2>T1)'};
matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = {
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV005/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV008/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV010/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV012/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV013/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV014/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV016/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV017/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV018/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV020/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV021/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV023/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV024/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV027/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV028/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV030/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV036/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV038/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV039/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV040/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV041/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV042/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV043/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV044/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV046/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV047/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV048/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV049/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV050/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV051/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV052/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV053/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV054/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV055/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV056/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV057/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV058/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV059/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV060/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV061/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV062/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV063/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV065/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV066/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV067/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV068/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV069/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV070/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV071/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV073/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV074/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV075/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV076/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV079/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV081/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV083/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV084/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV086/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV087/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV088/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV089/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV090/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV091/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV093/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV094/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV096/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV097/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV099/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV100/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV101/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV102/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV103/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV104/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV107/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV108/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV109/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV110/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV112/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV113/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV115/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV116/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV119/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV120/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV121/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV122/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV124/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV126/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV127/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV128/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV129/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV130/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV132/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV133/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV134/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV135/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV138/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV139/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV140/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV141/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV144/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV145/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV147/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV149/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV151/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV153/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV154/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV155/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV156/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV157/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV158/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV159/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV161/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV164/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV167/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV179/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV182/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV186/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV187/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV189/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV190/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV191/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV192/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV193/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV197/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV198/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV199/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV201/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV203/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV206/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV208/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV209/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV215/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV220/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV224/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV230/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV231/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV232/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV233/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV235/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV236/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV238/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV239/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV240/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV241/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV244/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV246/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV247/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV251/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV252/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV254/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV256/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV257/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV258/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV259/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV260/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV261/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV262/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV263/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV264/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV267/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV268/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV269/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV271/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV272/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV275/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV277/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV282/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV283/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV285/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV286/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV291/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV292/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV294/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV296/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV298/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV303/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV305/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV306/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV308/spmT_0001.nii,1'
'/Users/denicia/DEV/nonbids_data/fMRI/fx/models/WTP/all_waves/conditions/sub-DEV312/spmT_0001.nii,1'

                                                          };
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
matlabbatch{3}.spm.stats.con.spmmat(1) = cfg_dep('Model estimation: SPM.mat File', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{3}.spm.stats.con.consess{1}.tcon.name = 'HealthyLiked(T2>T1)';
matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = 1;
matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 1;
matlabbatch{4}.spm.stats.results.spmmat(1) = cfg_dep('Contrast Manager: SPM.mat File', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{4}.spm.stats.results.conspec.titlestr = '';
matlabbatch{4}.spm.stats.results.conspec.contrasts = 1;
matlabbatch{4}.spm.stats.results.conspec.threshdesc = 'FWE';
matlabbatch{4}.spm.stats.results.conspec.thresh = 0.05;
matlabbatch{4}.spm.stats.results.conspec.extent = 0;
matlabbatch{4}.spm.stats.results.conspec.conjunction = 1;
matlabbatch{4}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{4}.spm.stats.results.units = 1;
matlabbatch{4}.spm.stats.results.export{1}.ps = true;
matlabbatch{4}.spm.stats.results.export{2}.fig = true;
matlabbatch{4}.spm.stats.results.export{3}.png = true;
