%-----------------------------------------------------------------------
% Job saved on 16-Mar-2022 09:47:13 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
spm('defaults','fMRI');
matlabbatch{1}.spm.stats.factorial_design.dir = {'/Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts/fMRI/fx/models/SST/level2/posterror_cues_with_drt_20230410/CorrectGoFollowingCorrectStopxCgfcspost_pre_drt'};
matlabbatch{1}.spm.stats.factorial_design.des.t1.scans = {
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV006/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV008/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV013/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV014/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV015/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV016/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV017/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV018/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV019/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV020/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV021/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV022/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV023/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV024/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV026/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV027/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV028/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV029/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV030/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV031/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV033/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV034/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV035/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV036/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV037/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV038/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV040/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV041/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV042/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV043/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV044/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV045/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV046/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV047/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV048/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV049/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV051/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV052/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV053/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV054/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV055/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV056/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV057/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV058/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV059/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV060/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV062/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV063/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV064/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV065/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV066/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV067/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV070/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV071/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV072/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV073/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV074/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV075/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV076/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV077/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV078/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV079/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV080/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV081/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV082/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV083/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV084/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV085/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV086/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV087/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV088/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV089/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV090/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV093/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV095/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV096/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV097/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV099/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV100/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV102/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV103/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV104/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV105/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV106/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV107/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV108/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV109/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV110/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV111/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV112/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV113/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV114/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV115/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV116/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV117/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV118/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV119/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV120/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV121/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV122/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV123/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV124/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV126/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV127/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV128/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV129/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV130/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV131/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV132/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV133/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV134/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV135/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV137/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV139/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV140/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV141/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV144/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV145/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV147/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV149/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV150/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV151/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV154/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV155/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV156/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV157/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV158/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV159/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV161/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV164/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV166/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV167/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV168/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV169/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV170/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV171/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV172/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV173/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV174/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV177/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV178/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV179/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV180/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV182/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV183/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV187/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV188/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV191/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV192/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV193/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV194/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV195/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV196/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV197/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV198/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV199/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV200/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV201/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV202/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV204/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV205/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV206/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV208/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV209/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV210/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV215/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV216/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV217/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV220/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV222/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV223/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV224/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV225/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV228/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV230/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV232/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV233/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV235/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV236/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV237/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV238/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV239/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV240/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV241/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV243/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV246/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV249/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV250/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV251/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV252/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV253/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV254/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV255/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV256/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV257/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV258/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV259/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV260/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV261/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV262/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV263/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV264/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV265/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV266/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV267/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV268/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV269/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV270/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV271/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV272/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV273/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV274/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV275/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV276/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV277/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV278/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV282/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV284/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV285/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV290/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV291/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV292/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV293/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV294/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV295/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV296/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV297/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV298/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV299/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV300/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV302/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV303/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV304/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV305/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV306/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV307/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV308/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV309/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV310/beta_0006.nii,1'
'/Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/posterror_cues_with_drt/sub-DEV311/beta_0006.nii,1'

                                                          };
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
matlabbatch{3}.spm.stats.con.spmmat(1) = cfg_dep('Model estimation: SPM.mat File', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{3}.spm.stats.con.consess{1}.tcon.name = 'CorrectGoFollowingCorrectStopxCgfcspost_pre_drt';
matlabbatch{3}.spm.stats.con.consess{1}.tcon.weights = 1;
matlabbatch{3}.spm.stats.con.consess{1}.tcon.sessrep = 'none';
matlabbatch{3}.spm.stats.con.delete = 1;
matlabbatch{4}.spm.stats.results.spmmat(1) = cfg_dep('Contrast Manager: SPM.mat File', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{4}.spm.stats.results.conspec.titlestr = '';
matlabbatch{4}.spm.stats.results.conspec.contrasts = 1;
matlabbatch{4}.spm.stats.results.conspec.threshdesc = 'FWE';
matlabbatch{4}.spm.stats.results.conspec.thresh = 0.05;
matlabbatch{4}.spm.stats.results.conspec.extent = 0;
matlabbatch{4}.spm.stats.results.conspec.conjunction = 1;
matlabbatch{4}.spm.stats.results.conspec.mask.none = 1;
matlabbatch{4}.spm.stats.results.units = 1;
matlabbatch{4}.spm.stats.results.export{1}.ps = true;
matlabbatch{4}.spm.stats.results.export{2}.fig = true;
matlabbatch{4}.spm.stats.results.export{3}.png = true;
