sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_1_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_1 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_1/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_1_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_factor_2_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_factor_2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_factor_2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_factor_2_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_stop_cg_spatially_concatenated.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_stop_cg_spatially_concatenated/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_failed_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_failed_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_self referential_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Frontal Orbital Cortex.nii.gz" -t 30 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Frontal Orbital Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford/harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.nii.gz" -t 30 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Cingulate Gyrus, anterior division.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative affect_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_negative affect_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/emotion regulation_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_emotion regulation_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/harvardoxford-cortical_prob_Frontal Medial Cortex.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_harvardoxford-cortical_prob_Frontal Medial Cortex.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/negative emotions_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_negative emotions_association-test_z_FDR_0.pkl"

sbatch run_sr_learning_script.sbatch ml-ns_on_self_report_batch.py -m "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/masks/failure_related/self referential_association-test_z_FDR_0.01.nii.gz" -t 0 -r RTFS_f1_minus_f2 -s /SST/Brain_Data_posterror_conditions_84subs_post_correct_stop_cg_w_supplementary.pkl -o "/gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml/SST/regress_sr_RTFS_f1_minus_f2/post_correct_stop_cg_w_supplementary/regress_sr_no_zscore_RTFS_f1_minus_f2_84subs_self referential_association-test_z_FDR_0.pkl"


