default:
  nonbids_data_path: /gpfs/projects/sanlab/shared/DEV/nonbids_data/
  ml_data_folderpath: /gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml  
Benjamins-MacBook-Pro-2.local:
  sst_wave1_path:  /Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/
  spm_l2_script_template_filepath: /Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts/fMRI/fx/models/SST/level2/template_one_sample_design_estimate.m
  nonbids_data_path: /Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/
  dev_scripts_path: '/Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts'
  sst_level_2_path: /Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts/fMRI/fx/models/SST/level2/
  dropbox_datapath: /Users/benjaminsmith/Dropbox (University of Oregon)/UO-SAN Lab/Berkman Lab/Devaluation/analysis_files/data/
  spm_path: /Users/benjaminsmith/spm12
  
dyn-10-109-32-78.wless.uoregon.edu:
  nonbids_data_path: /gpfs/projects/sanlab/shared/DEV/nonbids_data/
  ml_data_folderpath: /gpfs/projects/sanlab/shared/DEV/nonbids_data/fMRI/ml
n138:
  nonbids_data_path:  /gpfs/projects/sanlab/shared/DEV/nonbids_data/
n222:
  nonbids_data_path:  /gpfs/projects/sanlab/shared/DEV/nonbids_data/
