UO-2010763:
  sst_wave1_path:  /Users/bensmith/Documents/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/
  nonbids_data_path: /Users/bensmith/Documents/data/DEV/nonbids_data/
  dev_scripts_path: '/Users/bensmith/Documents/code/DEV_scripts'
  dropbox_datapath: /Users/bensmith/Dropbox (University of Oregon)/UO-SAN Lab/Berkman Lab/Devaluation/analysis_files/data/
Benjamins-MacBook-Pro-2.local:
  sst_wave1_path:  /Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/fMRI/fx/models/SST/wave1/
  spm_l2_script_template_filepath: /Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts/fMRI/fx/models/SST/level2/template_one_sample_design_estimate.m
  nonbids_data_path: /Users/benjaminsmith/Google Drive/oregon/data/DEV/nonbids_data/
  dev_scripts_path: '/Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts'
  sst_level_2_path: /Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts/fMRI/fx/models/SST/level2/
  dropbox_datapath: /Users/benjaminsmith/Dropbox (University of Oregon)/UO-SAN Lab/Berkman Lab/Devaluation/analysis_files/data/
  spm_path: /Users/benjaminsmith/spm12
other: 
  dev_scripts_path: '/Users/benjaminsmith/Google Drive/oregon/code/DEV_scripts'